SET SERVEROUT    ON;


create or replace procedure sp_registrar_empleado(
P_REGISTRO_EMPLEADO EMPLEADOS%ROWTYPE,
P_CODIGO_RESULTADO OUT NUMBER,
P_MENSAJE_RESULTADO OUT VARCHAR2
) AS
V_ID_JEFE NUMBER;

BEGIN 

IF P_REGISTRO_EMPLEADO.NOMBRE IS NULL OR P_REGISTRO_EMPLEADO.APELLIDO  IS NULL THEN 
    P_MENSAJE_RESULTADO := 'EL NOMBRE O APELLIDO NO PUEDE SER NULO. ';
    P_CODIGO_RESULTADO := 1000;
    RETURN;
    
END IF;
  
IF TO_DATE(P_REGISTRO_EMPLEADO.FECHA_NAC, 'DD-MM-YYYY') > TO_DATE('31-12-2008', 'DD-MM-YYYY' ) THEN
    P_MENSAJE_RESULTADO := 'LA FECHA ES MAYOR AL 31-12-2008';
     P_CODIGO_RESULTADO := 1001;
      RETURN;
     END IF;
     
     
IF P_REGISTRO_EMPLEADO.SALARIO <= 15000 THEN
    P_MENSAJE_RESULTADO := 'EL SALARIO ES MENOR A 15,000';
     P_CODIGO_RESULTADO := 1002;
      RETURN;
     END IF;
     
     
     
 -----   
SELECT REPORTA_A INTO V_ID_JEFE FROM EMPLEADOS WHERE EMPLEADOID = P_REGISTRO_EMPLEADO.REPORTA_A;

IF V_ID_JEFE IS NULL THEN
P_MENSAJE_RESULTADO := 'NO EXISTE EL JEFE. ';
     P_CODIGO_RESULTADO := 1003;
     RETURN;
         
END IF;

P_CODIGO_rESULTADO := 0;
P_MENSAJE_RESULTADO := 'REGISTRO INSERTADO CON EXITO';

INSERT INTO EMPLEADOS VALUES (
P_REGISTRO_EMPLEADO.EMPLEADOID,
P_REGISTRO_EMPLEADO.NOMBRE,
P_REGISTRO_EMPLEADO.APELLIDO,
P_REGISTRO_EMPLEADO.FECHA_NAC,
P_REGISTRO_EMPLEADO.REPORTA_A,
P_REGISTRO_EMPLEADO.EXTENSION,
P_REGISTRO_EMPLEADO.SALARIO
);


EXCEPTION 

WHEN NO_DATA_FOUND THEN 
P_CODIGO_RESULTADO := -11;
P_MENSAJE_RESULTADO := 'NO SE ENCONTRO EL JEFE';

WHEN TOO_MANY_ROWS THEN 
P_CODIGO_RESULTADO := -10;
P_MENSAJE_RESULTADO := 'LLAVE DUPLICADA';

WHEN OTHERS THEN 
P_CODIGO_RESULTADO := -1;
P_MENSAJE_RESULTADO := 'ERROR AL INSERTAR';


END;










DECLARE
V_REGISTRO_EMPLEADO EMPLEADOS%ROWTYPE;
V_MENSAJE VARCHAR2(50);
V_CODIGO NUMBER;

BEGIN 

V_REGISTRO_EMPLEADO.EMPLEADOID  := 12;
V_REGISTRO_EMPLEADO.NOMBRE := 'ELIEL' ;
V_REGISTRO_EMPLEADO.APELLIDO :=  'OSEGUERA';
V_REGISTRO_EMPLEADO.FECHA_NAC := TO_DATE('01-01-2006', 'DD-MM-YYYY');
V_REGISTRO_EMPLEADO.REPORTA_A := 10;
V_REGISTRO_EMPLEADO.EXTENSION := 980;
V_REGISTRO_EMPLEADO.SALARIO := 16000 ;

SP_REGISTRAR_EMPLEADO(V_REGISTRO_EMPLEADO,V_CODIGO, V_MENSAJE);

DBMS_OUTPUT.PUT_LINE(V_MENSAJE);
DBMS_OUTPUT.PUT_LINE(V_CODIGO);


END;


SELECT * FROM EMPLEADOS WHERE EMPLEADOID = 13;




