--- consultas tarea 2

-- consulta tabla tiempo 
SELECT * FROM ( SELECT CONVERT(DATE, ORDER_DATE) tiempoId, DATEPART(YEAR, ORDER_DATE) año, 
DATEPART(MONTH, ORDER_DATE) mes, DATENAME(WEEKDAY, ORDER_DATE) dia,
((DATEPART(MONTH, ORDER_DATE)-1)/6)+1 semestre, 
DATEPART(QUARTER, ORDER_DATE) trimestre, DATEPART(WEEK, ORDER_DATE) num_semana
FROM DB_VENTAS.DBO.orders
GROUP BY DB_VENTAS.DBO.orders.ORDER_DATE ) as Tabla_Tiempo
WHERE NOT EXISTS(SELECT 1 FROM DW_VENTAS.DBO.DIM_TIEMPO WHERE
DW_VENTAS.DBO.DIM_TIEMPO.TIEMPO_ID = Tabla_Tiempo.tiempoId);



--- consultas tabla dim categorias 

SELECT * FROM DB_VENTAS.DBO.PRODUCT_CATEGORIES
WHERE NOT EXISTS(SELECT 1 FROM DW_VENTAS.DBO.DIM_CATEGORIA WHERE
DW_VENTAS.DBO.DIM_CATEGORIA.CATEGORIA_ID = DB_VENTAS.DBO.PRODUCT_CATEGORIES.CATEGORY_ID)


-- consultas tabla dim productos 


SELECT * FROM DB_VENTAS.DBO.PRODUCTS 
WHERE NOT EXISTS(SELECT 1 FROM DW_VENTAS.DBO.DIM_PRODUCTO WHERE
DW_VENTAS.DBO.DIM_PRODUCTO.PRODUCTO_ID = DB_VENTAS.DBO.PRODUCTS.PRODUCT_ID);