--- consultas tarea 2

-- consulta tabla tiempo 
SELECT * FROM ( SELECT CONVERT(DATE, ORDER_DATE) tiempoId, DATEPART(YEAR, ORDER_DATE) año, 
DATEPART(MONTH, ORDER_DATE) mes, DATENAME(WEEKDAY, ORDER_DATE) dia,
((DATEPART(MONTH, ORDER_DATE)-1)/6)+1 semestre, 
DATEPART(QUARTER, ORDER_DATE) trimestre, DATEPART(WEEK, ORDER_DATE) num_semana
FROM DB_VENTAS.DBO.orders
GROUP BY DB_VENTAS.DBO.orders.ORDER_DATE ) as Tabla_Tiempo
WHERE NOT EXISTS(SELECT 1 FROM DW_VENTAS.DBO.DIM_TIEMPO WHERE
DW_VENTAS.DBO.DIM_TIEMPO.TIEMPO_ID = Tabla_Tiempo.tiempoId);



--- consultas tabla dim categorias 

SELECT * FROM DB_VENTAS.DBO.PRODUCT_CATEGORIES
WHERE NOT EXISTS(SELECT 1 FROM DW_VENTAS.DBO.DIM_CATEGORIA WHERE
DW_VENTAS.DBO.DIM_CATEGORIA.CATEGORIA_ID = DB_VENTAS.DBO.PRODUCT_CATEGORIES.CATEGORY_ID)


-- consultas tabla dim productos 


SELECT * FROM DB_VENTAS.DBO.PRODUCTS 
WHERE NOT EXISTS(SELECT 1 FROM DW_VENTAS.DBO.DIM_PRODUCTO WHERE
DW_VENTAS.DBO.DIM_PRODUCTO.PRODUCTO_ID = DB_VENTAS.DBO.PRODUCTS.PRODUCT_ID);




------- DIM REGION



SELECT REGION_ID, REGION_NAME FROM REGIONS
WHERE NOT EXISTS(SELECT 1 FROM DW_VENTAS.DBO.DIM_region WHERE
DW_VENTAS.DBO.DIM_region.region_ID = DB_VENTAS.DBO.regions.region_ID);


--- DIM COUNTRIES

SELECT COUNTRY_ID, COUNTRY_NAME, REGION_ID FROM COUNTRIES
WHERE NOT EXISTS(SELECT 1 FROM DW_VENTAS.DBO.DIM_COUNTRY WHERE
DW_VENTAS.DBO.DIM_COUNTRY.COUNTRY_ID = DB_VENTAS.DBO.COUNTRIES.COUNTRY_ID)



-- DIM_UBICACION 


SELECT 
A.LOCATION_ID, 
A.ADDRESS, 
A.POSTAL_CODE, 
A.CITY, 
A.STATE, 
B.WAREHOUSE_ID, 
B.WAREHOUSE_NAME,
A.COUNTRY_ID
FROM DB_VENTAS.DBO.LOCATIONS A 
INNER JOIN DB_VENTAS.DBO.WAREHOUSES B ON A.LOCATION_ID = B.LOCATION_ID
WHERE NOT EXISTS (SELECT 1 FROM DW_VENTAS.DBO.DIM_UBICACION LOC WHERE
LOC.LOCATION_ID =A.location_id);


------ DIM FACT
select * from (
SELECT 
A.PRODUCT_ID AS PRODUCTO, 
CONVERT(DATE, C.ORDER_DATE) as tiempo_id,
E.LOCATION_ID as location_id,
sum(A.quantity) as cantidad, 
B.STANDARD_COST AS COSTO_ESTANDAR, 
SUM(A.QUANTITY*A.UNIT_PRICE) AS INGRESO_TOTAL,
SUM(A.QUANTITY*B.STANDARD_COST) AS COSTO_TOTAL,
( SUM(A.QUANTITY*A.UNIT_PRICE) - SUM(A.QUANTITY*B.STANDARD_COST) ) AS GANANCIA
FROM ORDER_ITEMS AS A 
INNER JOIN PRODUCTS AS B ON A.PRODUCT_ID = B.PRODUCT_ID 
INNER JOIN ORDERS AS C ON A.ORDER_ID = C.ORDER_ID 
INNER JOIN  INVENTORIES AS D ON B.PRODUCT_ID = D.PRODUCT_ID 
INNER JOIN WAREHOUSES AS E ON D.WAREHOUSE_ID = E.WAREHOUSE_ID 
GROUP BY A.PRODUCT_ID, 
C.ORDER_DATE,
E.LOCATION_ID, 
B.STANDARD_COST ) as ORIGEN_VENTAS 
WHERE NOT EXISTS ( SELECT 1 FROM  DW_VENTAS.DBO.FACT_VENTAS DESTINO
WHERE ORIGEN_VENTAS.PRODUCTO = DESTINO.producto_id AND 
ORIGEN_VENTAS.tiempo_id = DESTINO.tiempo_id AND 
ORIGEN_VENTAS.location_id = DESTINO.location_id 

);