declare begin
   delete from PRODUCTOS;
   DBMS_OUTPUT.PUT_LINE(sql%ROWCOUNT);
   delete from CATEGORIAS;
   DBMS_OUTPUT.PUT_LINE(sql%ROWCOUNT);
end;
/


   set SERVEROUTPUT on;



/

select *
  from PROVEEDORES;

declare
   -- type T_FILA is record (
   --       COD_PROV PROVEEDORES.PROVEEDORID%type,
   --       NOM_PROV PROVEEDORES.NOMBREPROV%type,
   --       CONTACTO PROVEEDORES.CONTACTO%type,
   --       CELULAR  PROVEEDORES.CELUPROV%type,
   --       FIJO     PROVEEDORES.FIJOPROV%type
   -- );
   -- type T_TABLA_PROVEEDORES is
   --    table of T_FILA;
   -- V_DATOS_PROVEEDORES T_TABLA_PROVEEDORES;

   type T_TABLA_PROVEEDORES is
      table of PROVEEDORES%ROWTYPE;
   V_DATOS_PROVEEDORES T_TABLA_PROVEEDORES;
begin
   select *
   bulk collect
     into V_DATOS_PROVEEDORES
     from PROVEEDORES;

   for NUMFILA in 1..sql%ROWCOUNT loop
      DBMS_OUTPUT.PUT_LINE('CODIGO DE PROVEEDOR: ' || V_DATOS_PROVEEDORES(NUMFILA).PROVEEDORID);
      DBMS_OUTPUT.PUT_LINE('NOMBRE DE PROVEEDOR: ' || V_DATOS_PROVEEDORES(NUMFILA).NOMBREPROV);
      DBMS_OUTPUT.PUT_LINE('CONTACTO DE PROVEEDOR: ' || V_DATOS_PROVEEDORES(NUMFILA).CONTACTO);
      DBMS_OUTPUT.PUT_LINE('CELULAR DE PROVEEDOR: ' || V_DATOS_PROVEEDORES(NUMFILA).CELUPROV);
      DBMS_OUTPUT.PUT_LINE('TELEFONO FIJO DE PROVEEDOR: ' || V_DATOS_PROVEEDORES(NUMFILA).FIJOPROV);
      DBMS_OUTPUT.PUT_LINE(CHR(13));
   end loop;
end;
/

   SET SERVEROUTPUT ON;
/

select TO_CHAR(
   SYSDATE,
   'MM DD YYYY'
) as FECHA
  from DUAL;

select TO_CHAR(
   SYSDATE,
   'FMMONTH DD YYYY'
) as FECHA
  from DUAL;

select TO_CHAR(
   SYSDATE,
   'DD-MM-YYYY'
) as FECHA
  from DUAL;